[package]
name = "redox-type-checker"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
tracing.workspace = true
redox-ast.workspace = true
thiserror.workspace = true
